server:
  port: 9001

#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clines?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    oauth.server.dao: debug
    oauth.server.config: debug
